name: CI

on:
  pull_request:
    paths:
      - '**/*.py'
      - 'mcp_server/pyproject.toml'
      - '.github/workflows/ci.yml'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up uv
        uses: astral-sh/setup-uv@v6
      - name: Install dependencies
        run: uv sync --dev
        working-directory: mcp_server
      - name: Run ruff
        run: uv run ruff .
        working-directory: mcp_server
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: Set up uv
        uses: astral-sh/setup-uv@v6
      - name: Install dependencies
        run: uv sync --dev
        working-directory: mcp_server
      - name: Run tests
        run: uv run pytest tests/ -v
        working-directory: mcp_server 