name: PR Builds

on:
  pull_request:
    paths:
      - '**/*.py'
      - 'mcp_server/pyproject.toml'
      - '.github/workflows/pr-builds.yml'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up uv
        uses: astral-sh/setup-uv@v6
      - name: Install dependencies
        run: uv sync --dev
        working-directory: mcp_server
      - name: Run ruff check
        run: uv run ruff check .
        working-directory: mcp_server
      - name: Run ruff format (check only)
        run: uv run ruff format --check .
        working-directory: mcp_server
      - name: Run tests
        run: uv run pytest tests/ -v
        working-directory: mcp_server 